#!/usr/bin/env python3
"""Reproduce the six scPerturBench metrics for WitnessCell on one dataset.

The implementation follows ``calPerformance_genetic.py`` and pertpy 0.7:
PCC-delta and MSE on pseudobulk means; Euclidean energy distance; Gaussian
symmetric KL followed by log2(1+x); OTT-JAX entropic Wasserstein; and top-100
Common-DEG overlap.  Distributional inputs are deterministically generated by
``export_result_h5ad.py``'s frozen Gaussian/control-variance contract.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from functools import lru_cache
from pathlib import Path

import anndata as ad
import h5py
import jax
import jax.numpy as jnp
import numpy as np
import pandas as pd
from ott.geometry.pointcloud import PointCloud
from ott.problems.linear.linear_problem import LinearProblem
from ott.solvers.linear.sinkhorn import Sinkhorn


EPS = 1e-8


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def pearson(left: np.ndarray, right: np.ndarray) -> float:
    left = left - left.mean()
    right = right - right.mean()
    denominator = np.linalg.norm(left) * np.linalg.norm(right)
    return float(np.sum(left * right) / max(float(denominator), 1e-12))


def welch_scores(
    x_mean: np.ndarray,
    x_var: np.ndarray,
    x_n: int,
    y_mean: np.ndarray,
    y_var: np.ndarray,
    y_n: int,
) -> np.ndarray:
    x_unbiased = x_var * x_n / max(x_n - 1, 1)
    y_unbiased = y_var * y_n / max(y_n - 1, 1)
    denominator = np.sqrt(
        x_unbiased / max(x_n, 1) + y_unbiased / max(y_n, 1)
    )
    return (x_mean - y_mean) / np.maximum(denominator, 1e-12)


def official_subsample(
    predicted: np.ndarray, observed: np.ndarray, maximum: int
) -> tuple[np.ndarray, np.ndarray]:
    # The official f_subSample() resets NumPy's legacy RNG to 42 on every
    # perturbation/metric call and samples imputed before stimulated cells.
    np.random.seed(42)
    if len(predicted) > maximum:
        predicted = predicted[
            np.random.choice(len(predicted), maximum, replace=False)
        ]
    if len(observed) > maximum:
        observed = observed[
            np.random.choice(len(observed), maximum, replace=False)
        ]
    return predicted, observed


def edistance(
    predicted: np.ndarray,
    observed: np.ndarray,
    observed_within: float | None = None,
) -> tuple[float, float]:
    within_predicted = mean_euclidean_distance(predicted, predicted)
    if observed_within is None:
        observed_within = mean_euclidean_distance(observed, observed)
    between = mean_euclidean_distance(predicted, observed)
    return 2.0 * between - within_predicted - observed_within, observed_within


def mean_euclidean_distance(left: np.ndarray, right: np.ndarray) -> float:
    """Mean of the exact Euclidean pairwise-distance matrix via BLAS.

    This is algebraically identical to ``scipy.spatial.distance.cdist(...,
    metric='euclidean').mean()`` but evaluates the dot products with a
    multi-threaded double-precision GEMM.  Float64 is intentional: it makes the
    result agree with cdist to numerical precision instead of merely after the
    benchmark's four-decimal rounding.
    """
    left64 = np.asarray(left, dtype=np.float64)
    right64 = np.asarray(right, dtype=np.float64)
    left_norm = np.einsum("ij,ij->i", left64, left64)
    right_norm = np.einsum("ij,ij->i", right64, right64)
    squared = left_norm[:, None] + right_norm[None, :]
    squared -= 2.0 * (left64 @ right64.T)
    np.maximum(squared, 0.0, out=squared)
    np.sqrt(squared, out=squared)
    return float(squared.mean(dtype=np.float64))


def symmetric_kl(predicted: np.ndarray, observed: np.ndarray) -> float:
    pred_mean = predicted.mean(axis=0, dtype=np.float64)
    obs_mean = observed.mean(axis=0, dtype=np.float64)
    pred_std = predicted.std(axis=0, dtype=np.float64) + EPS
    obs_std = observed.std(axis=0, dtype=np.float64) + EPS
    difference = np.square(pred_mean - obs_mean)
    forward = (
        np.log(obs_std / pred_std)
        + (np.square(pred_std) + difference) / (2.0 * np.square(obs_std))
        - 0.5
    )
    reverse = (
        np.log(pred_std / obs_std)
        + (np.square(obs_std) + difference) / (2.0 * np.square(pred_std))
        - 0.5
    )
    return float(np.log2(1.0 + np.mean(forward + reverse)))


def power_of_two(value: int) -> int:
    return 1 << max(0, int(value - 1).bit_length())


@lru_cache(maxsize=None)
def _wasserstein_solver(bucket: int, dimensions: int):
    # Padding plus zero masses makes the numerical problem identical to the
    # unpadded PointCloud.  Geometry masks preserve the official relative
    # epsilon (0.05 times the mean valid squared-Euclidean cost) while bucketing
    # limits JAX recompilation to one graph per cell-count power of two.
    @jax.jit
    def solve(x, y, mask, mass):
        geometry = PointCloud(x, y, src_mask=mask, tgt_mask=mask)
        output = Sinkhorn()(LinearProblem(geometry, a=mass, b=mass))
        return output.reg_ot_cost, output.converged

    return solve


def wasserstein(predicted: np.ndarray, observed: np.ndarray) -> tuple[float, bool, int]:
    if len(predicted) != len(observed):
        raise ValueError("formal exporter requires equal imputed/stimulated cell counts")
    n, dimensions = predicted.shape
    bucket = power_of_two(n)
    x = np.zeros((bucket, dimensions), dtype=np.float32)
    y = np.zeros_like(x)
    x[:n] = predicted
    y[:n] = observed
    mask = np.arange(bucket) < n
    mass = np.zeros(bucket, dtype=np.float32)
    mass[:n] = 1.0 / n
    cost, converged = _wasserstein_solver(bucket, dimensions)(x, y, mask, mass)
    return float(cost), bool(converged), bucket


def population_moments(matrix: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    return (
        matrix.mean(axis=0, dtype=np.float64),
        matrix.var(axis=0, dtype=np.float64),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", type=Path, required=True)
    parser.add_argument("--prediction", type=Path, action="append", required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--max-cells", type=int, default=2000)
    parser.add_argument(
        "--limit-conditions",
        type=int,
        default=None,
        help="Engineering smoke only: score the first N archived conditions.",
    )
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    backed = ad.read_h5ad(args.data, backed="r")
    labels = backed.obs["perturbation"].astype(str).to_numpy()
    with h5py.File(args.data, "r") as handle:
        if not isinstance(handle["X"], h5py.Dataset):
            raise TypeError("formal scorer currently requires the official dense HDF5 X")
        expression = handle["X"][:].astype(np.float32, copy=False)
    control = expression[labels == "control"]
    control_mean, control_var = population_moments(control)
    control_n = len(control)

    observed_cache: dict[str, np.ndarray] = {}
    order_cache: dict[str, np.ndarray] = {}
    observed_within_cache: dict[tuple[str, int], float] = {}
    manifests = []

    for prediction_path in args.prediction:
        archive = np.load(prediction_path, allow_pickle=False)
        dataset = str(archive["dataset"])
        seed = int(archive["seed"])
        checkpoint = args.out / f"raw_seed{seed}.csv"
        if checkpoint.exists() and not args.force:
            print(f"REUSE {checkpoint}")
            continue
        if not np.array_equal(
            archive["genes"].astype(str), backed.var_names.astype(str).to_numpy()
        ):
            raise ValueError("prediction/source gene identity mismatch")
        rng = np.random.default_rng(1000003 + seed)
        rows = []
        water_audit = []
        conditions = archive["conditions"].astype(str)
        if args.limit_conditions is not None:
            if args.limit_conditions < 1:
                raise ValueError("--limit-conditions must be positive")
            conditions = conditions[: args.limit_conditions]
        for number, condition in enumerate(conditions, start=1):
            if condition not in observed_cache:
                observed_cache[condition] = expression[labels == condition]
            observed = observed_cache[condition]
            n = len(observed)
            predicted = rng.normal(
                loc=archive["prediction"][number - 1].astype(np.float64),
                scale=np.sqrt(np.maximum(control_var, 0.0)),
                size=(n, expression.shape[1]),
            ).astype(np.float32)

            obs_mean, obs_var = population_moments(observed)
            pred_mean, pred_var = population_moments(predicted)
            if condition not in order_cache:
                true_scores = welch_scores(
                    obs_mean, obs_var, n,
                    control_mean, control_var, control_n,
                )
                order_cache[condition] = np.argsort(-np.abs(true_scores), kind="stable")
            true_order = order_cache[condition]
            pred_scores = welch_scores(
                pred_mean, pred_var, n,
                control_mean, control_var, control_n,
            )
            predicted_top100 = set(np.argsort(-np.abs(pred_scores), kind="stable")[:100])
            common_degs = len(predicted_top100.intersection(true_order[:100])) / 100.0

            for panel in (100, 5000):
                genes = true_order[: min(panel, expression.shape[1])]
                p = predicted[:, genes]
                o = observed[:, genes]
                p_mean = pred_mean[genes]
                o_mean = obs_mean[genes]
                c_mean = control_mean[genes]
                p_sub, o_sub = official_subsample(p, o, args.max_cells)

                metrics = {
                    "pearson_distance": pearson(p_mean - c_mean, o_mean - c_mean),
                    "mse": float(np.mean(np.square(p_mean - o_mean))),
                }
                cache_key = (condition, panel)
                energy, within_observed = edistance(
                    p_sub, o_sub, observed_within_cache.get(cache_key)
                )
                observed_within_cache[cache_key] = within_observed
                metrics["edistance"] = energy
                metrics["sym_kldiv"] = symmetric_kl(p_sub, o_sub)
                if panel == 100:
                    water, converged, bucket = wasserstein(p_sub, o_sub)
                    if not converged:
                        raise RuntimeError(
                            f"OTT Sinkhorn did not converge: {dataset} seed={seed} {condition}"
                        )
                    metrics["wasserstein"] = water
                    metrics["common_degs"] = common_degs
                    water_audit.append({
                        "condition": condition,
                        "cells": len(p_sub),
                        "bucket": bucket,
                        "converged": converged,
                    })

                for metric, value in metrics.items():
                    rows.append({
                        "performance": round(float(value), 4),
                        "metric": metric,
                        "DataSet": dataset,
                        "method": "WitnessCell",
                        "perturb": condition,
                        "DEG": panel,
                        "Ncontrol": control_n,
                        "Nimputed": n,
                        "Nstimulated": n,
                        "seed": seed,
                    })
            if number == 1 or number % 10 == 0 or number == len(conditions):
                print(f"{dataset} seed={seed}: {number}/{len(conditions)} conditions")

        pd.DataFrame(rows).to_csv(checkpoint, index=False)
        audit_path = args.out / f"wasserstein_audit_seed{seed}.json"
        audit_path.write_text(
            json.dumps(water_audit, indent=2) + "\n", encoding="utf-8"
        )
        manifests.append({
            "dataset": dataset,
            "seed": seed,
            "prediction": str(prediction_path.resolve()),
            "prediction_sha256": sha256(prediction_path),
            "conditions": len(conditions),
            "metric_rows": len(rows),
            "checkpoint": str(checkpoint),
        })

    raw_parts = sorted(args.out.glob("raw_seed*.csv"))
    if raw_parts:
        pd.concat([pd.read_csv(path) for path in raw_parts], ignore_index=True).to_csv(
            args.out / "official_six_metric_raw.csv", index=False
        )
    manifest = {
        "status": (
            "PASS_OFFICIAL_SIX_METRIC_SMOKE"
            if args.limit_conditions is not None
            else "PASS_OFFICIAL_SIX_METRIC_SCORING"
        ),
        "data": str(args.data.resolve()),
        "data_sha256": sha256(args.data),
        "shape": [int(expression.shape[0]), int(expression.shape[1])],
        "max_distribution_cells": args.max_cells,
        "condition_limit": args.limit_conditions,
        "claim_boundary": (
            "Engineering smoke only; no scientific inference."
            if args.limit_conditions is not None
            else "Formal full-condition scoring."
        ),
        "jax": jax.__version__,
        "ott_contract": "ott-jax PointCloud + LinearProblem + default Sinkhorn; squared-Euclidean cost; relative epsilon; all converged",
        "energy_distance_contract": "Exact Euclidean pairwise-distance mean evaluated by the norm/dot-product identity in float64; numerically equivalent to scipy cdist.",
        "metrics": [
            "PCC-delta", "MSE", "E-distance", "symmetric KL",
            "Wasserstein", "Common-DEGs",
        ],
        "runs_scored_now": manifests,
        "raw_parts": [str(path) for path in raw_parts],
    }
    (args.out / "score_manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
